/**
 * Cashpan setup script (v1).
 *
 * Steps:
 *   1. Publish the Move package (vault + yield_venue)
 *   2. Create YieldVenue and fund its reserve
 *   3. Create Vault bound to the venue
 *   4. Issue AgentCap to a fresh keypair
 *   5. Deposit initial liquid balance
 *   6. Write all IDs + agent key to .env
 *
 * Prerequisites:
 *   - `sui` CLI configured with the owner keypair as active address (testnet)
 *   - Run: tsx scripts/setup.ts
 *
 * The agent keypair is generated fresh and its private key is written to .env.
 * It can ONLY call rebalance(), bounded by per-tx and daily caps. Owner can revoke instantly.
 */

import { execSync } from "child_process";
import { readFileSync, writeFileSync, existsSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import { SuiJsonRpcClient } from "@mysten/sui/jsonRpc";
import { Ed25519Keypair } from "@mysten/sui/keypairs/ed25519";
import { Transaction } from "@mysten/sui/transactions";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const MOVE_DIR = join(ROOT, "move");

const RPC_URL = process.env.SUI_RPC_URL ?? "https://fullnode.testnet.sui.io:443";
const COIN_TYPE = "0x2::sui::SUI";

// Venue: 10% per epoch on testnet (easy to observe interest accruing quickly)
const RATE_BPS = 1_000n;       // 10%
const PERIOD_EPOCHS = 1n;      // per epoch
const RESERVE_FUND = 100_000_000n; // 0.1 SUI reserve (sufficient for testnet at 10%/epoch)

// Vault rebalance caps in MIST
const PER_TX_CAP = 500_000_000n;       // 0.5 SUI per rebalance tx
const DAILY_CAP = 2_000_000_000n;      // 2 SUI per epoch (rebalance)
// Vault outflow caps — separate, tighter limit for coin-out actions
const OUTFLOW_PER_TX_CAP = 100_000_000n; // 0.1 SUI per outflow tx
const OUTFLOW_DAILY_CAP = 500_000_000n;  // 0.5 SUI per epoch (outflow)
const INITIAL_FUND = 500_000_000n;     // 0.5 SUI initial liquid

// Buffer rule (written to .env for agent to read)
const BUFFER = 250_000_000n;  // 0.25 SUI target liquid
const BAND = 25_000_000n;     // 0.025 SUI dead-band

async function waitForTx(client: SuiJsonRpcClient, digest: string): Promise<void> {
  for (let i = 0; i < 20; i++) {
    try {
      const tx = await client.getTransactionBlock({ digest, options: {} });
      if (tx?.digest) return;
    } catch {
      // not finalized yet
    }
    await new Promise((r) => setTimeout(r, 1500));
  }
  throw new Error(`Transaction ${digest} not confirmed after 30s`);
}

async function main() {
  const client = new SuiJsonRpcClient({ url: RPC_URL });
  const ownerAddress = execSync("sui client active-address", { encoding: "utf8" }).trim();

  console.log("=== Cashpan v1 Setup ===\n");
  console.log(`Owner: ${ownerAddress}\n`);

  // ---- 1. Publish ----
  console.log("1. Publishing Move package...");
  // Clear any prior publication record so re-running setup works from scratch.
  writeFileSync(
    join(MOVE_DIR, "Published.toml"),
    "# Generated by Move\n# This file contains metadata about published versions of this package in different environments\n# This file SHOULD be committed to source control\n",
  );
  const publishOutput = execSync(
    `sui client publish --gas-budget 200000000 --json "${MOVE_DIR}"`,
    { encoding: "utf8" },
  );

  const publishResult = JSON.parse(publishOutput);
  if (publishResult.effects?.status?.status !== "success") {
    throw new Error(`Publish failed: ${JSON.stringify(publishResult.effects?.status)}`);
  }

  const packageId = publishResult.effects.created
    .find((obj: { owner: unknown }) => obj.owner === "Immutable")
    ?.reference?.objectId;
  if (!packageId) throw new Error("Could not find package ID in publish output");
  console.log(`   Package ID: ${packageId}`);

  // ---- 2. Create YieldVenue + fund reserve ----
  console.log("\n2. Creating YieldVenue and funding reserve...");
  const venueTx = new Transaction();
  venueTx.moveCall({
    target: `${packageId}::yield_venue::create_venue`,
    typeArguments: [COIN_TYPE],
    arguments: [venueTx.pure.u64(RATE_BPS), venueTx.pure.u64(PERIOD_EPOCHS)],
  });
  const venueCreateResult = await client.signAndExecuteTransaction({
    signer: ownerKeypair(),
    transaction: venueTx,
    options: { showEffects: true, showObjectChanges: true },
  });
  if (venueCreateResult.effects?.status.status !== "success") {
    throw new Error(`create_venue failed: ${venueCreateResult.effects?.status.error}`);
  }
  const venueId = venueCreateResult.objectChanges?.find(
    (c) => c.type === "created" && "objectType" in c && c.objectType.includes("YieldVenue"),
  )?.["objectId"];
  if (!venueId) throw new Error("Could not find YieldVenue ID");
  console.log(`   YieldVenue ID: ${venueId}`);
  await waitForTx(client, venueCreateResult.digest);

  const fundReserveTx = new Transaction();
  const [res] = fundReserveTx.splitCoins(fundReserveTx.gas, [RESERVE_FUND]);
  fundReserveTx.moveCall({
    target: `${packageId}::yield_venue::fund_reserve`,
    typeArguments: [COIN_TYPE],
    arguments: [fundReserveTx.object(venueId), res],
  });
  const fundReserveResult = await client.signAndExecuteTransaction({
    signer: ownerKeypair(),
    transaction: fundReserveTx,
    options: { showEffects: true },
  });
  if (fundReserveResult.effects?.status.status !== "success") {
    throw new Error(`fund_reserve failed: ${fundReserveResult.effects?.status.error}`);
  }
  console.log(`   Reserve funded: ${RESERVE_FUND} MIST`);
  await waitForTx(client, fundReserveResult.digest);

  // ---- 3. Create Vault (bound to venue) ----
  console.log("\n3. Creating Vault...");
  const createTx = new Transaction();
  const ownerCapResult = createTx.moveCall({
    target: `${packageId}::vault::create_vault`,
    typeArguments: [COIN_TYPE],
    arguments: [
      createTx.object(venueId),
      createTx.pure.address(ownerAddress), // payout_address = owner
      createTx.pure.u64(PER_TX_CAP),
      createTx.pure.u64(DAILY_CAP),
      createTx.pure.u64(OUTFLOW_PER_TX_CAP),
      createTx.pure.u64(OUTFLOW_DAILY_CAP),
    ],
  });
  createTx.transferObjects([ownerCapResult], ownerAddress);

  const createResult = await client.signAndExecuteTransaction({
    signer: ownerKeypair(),
    transaction: createTx,
    options: { showEffects: true, showObjectChanges: true },
  });
  if (createResult.effects?.status.status !== "success") {
    throw new Error(`create_vault failed: ${createResult.effects?.status.error}`);
  }

  const vaultId = createResult.objectChanges?.find(
    (c) => c.type === "created" && "objectType" in c && c.objectType.includes("::vault::Vault"),
  )?.["objectId"];
  const ownerCapId = createResult.objectChanges?.find(
    (c) => c.type === "created" && "objectType" in c && c.objectType.includes("OwnerCap"),
  )?.["objectId"];
  if (!vaultId || !ownerCapId) throw new Error("Could not find Vault or OwnerCap IDs");
  console.log(`   Vault ID:    ${vaultId}`);
  console.log(`   OwnerCap ID: ${ownerCapId}`);
  await waitForTx(client, createResult.digest);

  // ---- 4. Issue AgentCap to fresh keypair ----
  console.log("\n4. Issuing AgentCap...");
  const agentKeypair = new Ed25519Keypair();
  const agentAddress = agentKeypair.getPublicKey().toSuiAddress();
  console.log(`   Agent address: ${agentAddress}`);

  const issueTx = new Transaction();
  const agentCapResult = issueTx.moveCall({
    target: `${packageId}::vault::issue_agent_cap`,
    typeArguments: [COIN_TYPE],
    arguments: [issueTx.object(ownerCapId), issueTx.object(vaultId)],
  });
  issueTx.transferObjects([agentCapResult], agentAddress);

  const issueResult = await client.signAndExecuteTransaction({
    signer: ownerKeypair(),
    transaction: issueTx,
    options: { showEffects: true, showObjectChanges: true },
  });
  if (issueResult.effects?.status.status !== "success") {
    throw new Error(`issue_agent_cap failed: ${issueResult.effects?.status.error}`);
  }
  const agentCapId = issueResult.objectChanges?.find(
    (c) => c.type === "created" && "objectType" in c && c.objectType.includes("AgentCap"),
  )?.["objectId"];
  if (!agentCapId) throw new Error("Could not find AgentCap ID");
  console.log(`   AgentCap ID: ${agentCapId}`);
  await waitForTx(client, issueResult.digest);

  // ---- 5. Fund agent address with gas ----
  console.log("\n5. Funding agent address with gas...");
  const agentGasTx = new Transaction();
  const [agentGasCoin] = agentGasTx.splitCoins(agentGasTx.gas, [100_000_000n]); // 0.1 SUI
  agentGasTx.transferObjects([agentGasCoin], agentAddress);
  const agentGasResult = await client.signAndExecuteTransaction({
    signer: ownerKeypair(),
    transaction: agentGasTx,
    options: { showEffects: true },
  });
  if (agentGasResult.effects?.status.status !== "success") {
    throw new Error(`agent gas funding failed: ${agentGasResult.effects?.status.error}`);
  }
  console.log(`   Sent 0.1 SUI to agent ${agentAddress}`);
  await waitForTx(client, agentGasResult.digest);

  // ---- 7. Fund vault liquid ----
  console.log("\n7. Funding vault liquid...");
  const fundTx = new Transaction();
  const [fundCoin] = fundTx.splitCoins(fundTx.gas, [INITIAL_FUND]);
  fundTx.moveCall({
    target: `${packageId}::vault::deposit`,
    typeArguments: [COIN_TYPE],
    arguments: [fundTx.object(ownerCapId), fundTx.object(vaultId), fundCoin],
  });
  const fundResult = await client.signAndExecuteTransaction({
    signer: ownerKeypair(),
    transaction: fundTx,
    options: { showEffects: true },
  });
  if (fundResult.effects?.status.status !== "success") {
    throw new Error(`deposit failed: ${fundResult.effects?.status.error}`);
  }
  console.log(`   Deposited ${INITIAL_FUND} MIST into liquid`);

  // ---- 6. Write .env ----
  console.log("\n8. Writing .env...");
  const env = `# Generated by setup.ts (v1) — do not commit
SUI_RPC_URL=${RPC_URL}
PACKAGE_ID=${packageId}
VENUE_ID=${venueId}
VAULT_ID=${vaultId}
OWNER_CAP_ID=${ownerCapId}
AGENT_CAP_ID=${agentCapId}
AGENT_PRIVATE_KEY=${agentKeypair.getSecretKey()}
COIN_TYPE=${COIN_TYPE}
BUFFER=${BUFFER}
BAND=${BAND}
INTERVAL_MS=300000
`;
  writeFileSync(join(ROOT, ".env"), env);
  console.log(`   Wrote .env`);

  console.log("\n=== Setup complete ===");
  console.log("\nRun the agent:");
  console.log("  npm run agent\n");
  console.log("Explorer links:");
  console.log(`  Package: https://suiexplorer.com/object/${packageId}?network=testnet`);
  console.log(`  Venue:   https://suiexplorer.com/object/${venueId}?network=testnet`);
  console.log(`  Vault:   https://suiexplorer.com/object/${vaultId}?network=testnet`);
}

/** Load the keypair for the current `sui client active-address` from the keystore. */
function ownerKeypair(): Ed25519Keypair {
  const activeAddress = execSync("sui client active-address", { encoding: "utf8" }).trim();
  const keystorePath = join(process.env.HOME ?? "/root", ".sui", "sui_config", "sui.keystore");

  if (!existsSync(keystorePath)) {
    throw new Error(`Keystore not found at ${keystorePath}. Run 'sui client' first.`);
  }

  const keystore: string[] = JSON.parse(readFileSync(keystorePath, "utf8"));
  for (const entry of keystore) {
    const raw = Buffer.from(entry, "base64");
    if (raw[0] !== 0x00) continue; // skip non-Ed25519 entries
    const kp = Ed25519Keypair.fromSecretKey(raw.slice(1, 33));
    if (kp.getPublicKey().toSuiAddress() === activeAddress) return kp;
  }

  throw new Error(
    `No key in keystore matches active address ${activeAddress}. ` +
      `Run 'sui client switch --address <addr>' to select the right address.`,
  );
}

main().catch((e) => {
  console.error("Setup failed:", e);
  process.exit(1);
});
